name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Continous-Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Using SSH to VULTR VPS PROD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /apps/idejualan-hrms/
            git pull origin master
            composer install
            php artisan migrate
            npm install
